server:
  port: 80

spring:
  application:
    name: tryhook

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hook
    username: root
    password: King@mysq1

  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    #    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG